targets = [ "//:range" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
version = "1.43.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
version = "1.43.0"
