targets = [ "//:range" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
version = "1.33.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-iterator"
version = "1.33.1"
